#!/bin/sh
# pcrypt

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ];
then
        echo "Incorrect Syntax\nEncrypt: pcrypt <filename1> <filename2>\nDecrypt: pcrypt <filename>"
fi

# One argument
#       pcrypt <filename>
# Decrypts <filename>
if [ "$#" -eq 1 ]
then
        echo "Decrypting file '$1'..."
        openssl enc -d -aes256 -in $1 | tar --extract --file - --gzip
fi

# Two arguments
#       pcrypt <filename1> <filename2>
# Encrypts <filename1> to <filename2>

if [ "$#" -eq 2 ]
then
        echo "Encrypting file '$1' with name '$2'..."
        tar --create --file - --posix --gzip -- $1 | openssl enc -e -aes256 -out $2
fi
